[package]
name = "poltergeist"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.51", features = ["derive", "env"] }
crc32fast = "1.5.0"
hidapi = "2.6.3"
udev = "0.9.3"
log = "*"
env_logger = "*"
